--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FrostCheat/DeluxeVeinMiner
build-by-default: true
branches:
- main
projects:
  DeluxeVeinMiner:
    path: ""
    icon: "icon.png"
...
